import { useNoteRepository } from "@/application/notes/useNoteRepository";
import { usePayloadParser } from "@/application/notes/usePayloadParser";
import { useNotes } from "@/contexts/NotesProvider";
import { NoteContentType, ListContentType } from "@/domain/notes/types";
import { Pressable, StyleSheet, Text, View } from "react-native";
import 'react-native-get-random-values';
import { v4 as uuidv4 } from 'uuid';

const NOTE_CONTENT_SAMPLE = `<html><h1>Hello World!</h1><p>This is sample content generated by the app debugger.</p><ul><li>test</li><li>test 1</li><li>test 2</li><li>test 3</li><li>test 4</li></ul><h2>Another title</h2><ol><li><b>test</b> 5</li><li><u><i>test</i></u> 6</li><li>test 7</li><li>test 8</li><li>test 9</li></ol><blockquote>This is a blockquote</blockquote><h2>Another title</h2><ol><li><b>test</b> 5</li><li><u><i>test</i></u> 6</li><li>test 7</li><li>test 8</li><li>test 9</li></ol></html>`;


export default function Debugger() {
    const { reload } = useNotes();
    const noteRepo = useNoteRepository();
    const parser = usePayloadParser();
    const addNotes = async (n: number) => {
        for (let x = 0; x < n; x++) {
            if (x % 2 == 0) {
                const content: NoteContentType = {
                    html: NOTE_CONTENT_SAMPLE,
                    plainText: 'Hello World\n\nthis is example content',
                };
                await noteRepo.create(`Note ${x}`, parser.unparseContent(content) ?? '', 'note');
            } else {
                const content: ListContentType = {
                    items: [
                        { checked: false, content: 'Hello', id: uuidv4() },
                        { checked: true, content: 'Hello', id: uuidv4() },
                        { checked: true, content: 'Hello woooooooooorld', id: uuidv4() },
                        { checked: false, content: 'Hello', id: uuidv4() },
                        { checked: false, content: 'aaaaaaaaaaaaaaaaaa', id: uuidv4() },
                        { checked: false, content: 'Hello', id: uuidv4() },
                        { checked: false, content: 'Hello', id: uuidv4() },
                        { checked: true, content: 'Hello', id: uuidv4() },
                        { checked: true, content: 'Hello woooooooooorld', id: uuidv4() },
                        { checked: false, content: 'Hello', id: uuidv4() },
                        { checked: false, content: 'aaaaaaaaaaaaaaaaaa', id: uuidv4() },
                        { checked: false, content: 'Hello', id: uuidv4() },
                        { checked: false, content: 'Hello', id: uuidv4() },
                        { checked: true, content: 'Hello', id: uuidv4() },
                        { checked: true, content: 'Hello woooooooooorld', id: uuidv4() },
                        { checked: false, content: 'Hello', id: uuidv4() },
                        { checked: false, content: 'aaaaaaaaaaaaaaaaaa', id: uuidv4() },
                        { checked: false, content: 'Hello', id: uuidv4() },
                        { checked: false, content: 'Hello', id: uuidv4() },
                        { checked: true, content: 'Hello', id: uuidv4() },
                        { checked: true, content: 'Hello woooooooooorld', id: uuidv4() },
                        { checked: false, content: 'Hello', id: uuidv4() },
                        { checked: false, content: 'aaaaaaaaaaaaaaaaaa', id: uuidv4() },
                        { checked: false, content: 'Hello', id: uuidv4() },
                    ],
                };
                await noteRepo.create(`Note ${x}`, parser.unparseContent(content) ?? '', 'list');
            }
        }

        await reload();

    };

    const deleteAndReload = async () => {
        const allNotes = await noteRepo.getAll();
        await noteRepo.deleteAll(allNotes.map(note => note.id));
        await reload();
    };

    return (
        <View style={styles.debuggerContainer}>
            <Pressable 
            style={styles.pressable}
            onPress={async () => await deleteAndReload() }
            >
                <Text style={styles.pressableText}>X</Text>
            </Pressable>
            <Pressable
                style={styles.pressable}
                onPress={async () => await addNotes(10)}
            >
                <Text style={styles.pressableText}>+10</Text>
            </Pressable>
        </View>
    );
}

const styles = StyleSheet.create({
    debuggerContainer: {
        position: 'absolute',
        backgroundColor: '#a3fcffff',
        columnGap: 10,
        flexDirection: 'row',
        bottom: 70,
    },
    pressable: {
        backgroundColor: '#1bbeffff',
        paddingHorizontal: 30,
        paddingVertical: 10,
        justifyContent: 'center',
        alignItems: 'center'
    },
    pressableText: {
        fontSize: 18
    }
});